<?php

/*
 * This file is part of the Api Platform Laravel project.
 *
 * (c) Anthonius Munthi <https://itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Tests\ApiPlatformLaravel\Functional;

use ApiPlatformLaravel\Testing\InteractsWithORM;
use Tests\ApiPlatformLaravel\Functional\Concerns\InteractsWithUser;
use Tests\Dummy\Model\User;

class DoctrineIntegrationTest extends TestCase
{
    use InteractsWithORM;
    use InteractsWithUser;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->refreshDatabase();
    }

    public function testBoot()
    {
        /* @var \Symfony\Component\DependencyInjection\ContainerInterface $container */

        $this->assertNotNull($this->getRegistry()->getManagerForClass(User::class));
    }

    public function testResolvedTargetEntities()
    {
        $group = $this->createGroup();
        $user = $this->createUser();
        $user->setGroup($group);
        $this->store($user);

        $this->assertNotNull($user->getId());
        $this->assertEquals($group->getId(), $user->getGroup()->getId());
    }
}
