<?php

/*
 * This file is part of the Api Platform Laravel project.
 *
 * (c) Anthonius Munthi <https://itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace ApiPlatformLaravel;

use ApiPlatformLaravel\DependencyInjection\Compiler\FilterServicePass;
use Illuminate\Contracts\Container\Container as LaravelContainer;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class LaravelBundle extends Bundle
{
    /**
     * @var LaravelContainer
     */
    private $laravel;

    public function __construct(LaravelContainer $laravel)
    {
        $this->laravel = $laravel;
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $container->addCompilerPass(new FilterServicePass());
        $this->initLaravel($container);
    }

    private function initLaravel(ContainerBuilder $container)
    {
        $laravel = $this->laravel;
        $config = $laravel->get('config');
        $container->setParameter('laravel.orm.database_url', $config->get('api_platform.database_url'));

        $helper = $laravel->get('api');
        $compilers = $helper->getOrmCompilersPass();
        foreach ($compilers as $compiler) {
            $container->addCompilerPass($compiler);
        }

        $resolved = $helper->getResolvedEntities();
        $container->setParameter('laravel.orm.resolve_target_entities', $resolved);
    }
}
